//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prospekt.tel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class psEnt : DbContext
    {
        public psEnt()
            : base("name=psEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sex> sex { get; set; }
    
        public virtual ObjectResult<usp_GetAllCategories_Result> usp_GetAllCategories(string substr)
        {
            var substrParameter = substr != null ?
                new ObjectParameter("substr", substr) :
                new ObjectParameter("substr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllCategories_Result>("usp_GetAllCategories", substrParameter);
        }
    
        public virtual int usp_Ctegories_IU(Nullable<int> id, string category_desc, string createdBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var category_descParameter = category_desc != null ?
                new ObjectParameter("category_desc", category_desc) :
                new ObjectParameter("category_desc", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Ctegories_IU", idParameter, category_descParameter, createdByParameter);
        }
    
        public virtual int usp_Ctegories_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Ctegories_Delete", idParameter);
        }
    
        public virtual ObjectResult<usp_GetCategoryById_Result> usp_GetCategoryById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetCategoryById_Result>("usp_GetCategoryById", idParameter);
        }
    
        public virtual ObjectResult<usp_GetAllSubCategoriesByCategoryID_Result> usp_GetAllSubCategoriesByCategoryID(Nullable<int> catId, string substr)
        {
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("catId", catId) :
                new ObjectParameter("catId", typeof(int));
    
            var substrParameter = substr != null ?
                new ObjectParameter("substr", substr) :
                new ObjectParameter("substr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllSubCategoriesByCategoryID_Result>("usp_GetAllSubCategoriesByCategoryID", catIdParameter, substrParameter);
        }
    
        public virtual ObjectResult<usp_GetSubCategoryById_Result> usp_GetSubCategoryById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSubCategoryById_Result>("usp_GetSubCategoryById", idParameter);
        }
    
        public virtual int usp_SubCategories_IU(Nullable<int> id, Nullable<int> catId, string subcategory_desc, string createdBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("catId", catId) :
                new ObjectParameter("catId", typeof(int));
    
            var subcategory_descParameter = subcategory_desc != null ?
                new ObjectParameter("subcategory_desc", subcategory_desc) :
                new ObjectParameter("subcategory_desc", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SubCategories_IU", idParameter, catIdParameter, subcategory_descParameter, createdByParameter);
        }
    
        public virtual int usp_SubCategories_Delete(Nullable<int> id, string user)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_SubCategories_Delete", idParameter, userParameter);
        }
    
        public virtual ObjectResult<usp_GetAllProducts_Result> usp_GetAllProducts(Nullable<int> scat, string substr)
        {
            var scatParameter = scat.HasValue ?
                new ObjectParameter("scat", scat) :
                new ObjectParameter("scat", typeof(int));
    
            var substrParameter = substr != null ?
                new ObjectParameter("substr", substr) :
                new ObjectParameter("substr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllProducts_Result>("usp_GetAllProducts", scatParameter, substrParameter);
        }
    
        public virtual int usp_Products_IU(Nullable<int> id, Nullable<int> catId, Nullable<int> subCatId, string productName, string createdBy)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var catIdParameter = catId.HasValue ?
                new ObjectParameter("catId", catId) :
                new ObjectParameter("catId", typeof(int));
    
            var subCatIdParameter = subCatId.HasValue ?
                new ObjectParameter("subCatId", subCatId) :
                new ObjectParameter("subCatId", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("productName", productName) :
                new ObjectParameter("productName", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Products_IU", idParameter, catIdParameter, subCatIdParameter, productNameParameter, createdByParameter);
        }
    
        public virtual ObjectResult<usp_GetProductById_Result> usp_GetProductById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProductById_Result>("usp_GetProductById", idParameter);
        }
    
        public virtual int usp_Products_Delete(Nullable<int> id, string user)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Products_Delete", idParameter, userParameter);
        }
    
        public virtual ObjectResult<string> usp_GetPersonFIOLetters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetPersonFIOLetters");
        }
    
        public virtual ObjectResult<usp_GetPerson_Result> usp_GetPerson(string fam, string im, string ot)
        {
            var famParameter = fam != null ?
                new ObjectParameter("fam", fam) :
                new ObjectParameter("fam", typeof(string));
    
            var imParameter = im != null ?
                new ObjectParameter("im", im) :
                new ObjectParameter("im", typeof(string));
    
            var otParameter = ot != null ?
                new ObjectParameter("ot", ot) :
                new ObjectParameter("ot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPerson_Result>("usp_GetPerson", famParameter, imParameter, otParameter);
        }
    
        public virtual int usp_Persons_IU(Nullable<int> id, string fam, string im, string ot, Nullable<int> sex, Nullable<System.DateTime> birthday, string person_comment, string person_photo, string person_passport, string passport_serie, string passport_num, string cellPhone)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var famParameter = fam != null ?
                new ObjectParameter("fam", fam) :
                new ObjectParameter("fam", typeof(string));
    
            var imParameter = im != null ?
                new ObjectParameter("im", im) :
                new ObjectParameter("im", typeof(string));
    
            var otParameter = ot != null ?
                new ObjectParameter("ot", ot) :
                new ObjectParameter("ot", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(int));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("birthday", birthday) :
                new ObjectParameter("birthday", typeof(System.DateTime));
    
            var person_commentParameter = person_comment != null ?
                new ObjectParameter("person_comment", person_comment) :
                new ObjectParameter("person_comment", typeof(string));
    
            var person_photoParameter = person_photo != null ?
                new ObjectParameter("person_photo", person_photo) :
                new ObjectParameter("person_photo", typeof(string));
    
            var person_passportParameter = person_passport != null ?
                new ObjectParameter("person_passport", person_passport) :
                new ObjectParameter("person_passport", typeof(string));
    
            var passport_serieParameter = passport_serie != null ?
                new ObjectParameter("passport_serie", passport_serie) :
                new ObjectParameter("passport_serie", typeof(string));
    
            var passport_numParameter = passport_num != null ?
                new ObjectParameter("passport_num", passport_num) :
                new ObjectParameter("passport_num", typeof(string));
    
            var cellPhoneParameter = cellPhone != null ?
                new ObjectParameter("cellPhone", cellPhone) :
                new ObjectParameter("cellPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Persons_IU", idParameter, famParameter, imParameter, otParameter, sexParameter, birthdayParameter, person_commentParameter, person_photoParameter, person_passportParameter, passport_serieParameter, passport_numParameter, cellPhoneParameter);
        }
    
        public virtual ObjectResult<usp_GetSex_Result> usp_GetSex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetSex_Result>("usp_GetSex");
        }
    
        public virtual ObjectResult<usp_GetPersonById_Result> usp_GetPersonById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetPersonById_Result>("usp_GetPersonById", idParameter);
        }
    
        public virtual ObjectResult<string> usp_GetPersonPhoto(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetPersonPhoto", idParameter);
        }
    
        public virtual ObjectResult<string> usp_GetPersonPassScan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_GetPersonPassScan", idParameter);
        }
    }
}
