//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prospekt.tel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sex
    {
        public int id { get; set; }
        public string description { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
    }
}
